blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.home_page),
    path('article/<slug:slug>', views.ArticleDetailView.as_view(), name="article"),
    path('about/', views.AboutMeView.as_view(), name='about_me'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
    path('', include('perfiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfiles/urls.py
from django.urls import path
from django.views.generic import TemplateView

from perfiles import views 

app_name = 'perfiles'

urlpatterns = [
    path('registration/', views.PerfilRegistration.as_view(), name='registration' ),
    path('success/', TemplateView.as_view(template_name='perfiles/success_registration.html'), name='success')
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

from ckeditor.fields import RichTextField

# Create your models here.

class Articulo(models.Model):
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=255)
    cuerpo = RichTextField()
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    categories = models.ManyToManyField("Category")
    featured = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("blog:article", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-fecha"]

    def __str__(self):
        return self.titulo

class Category(models.Model):
    titulo = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"slug": self.slug})

    def __str__(self):
        return self.titulo

perfiles/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Perfil(AbstractUser):
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

perfiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model



class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

blog/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.db.models import Q

from blog.models import Articulo, Category


# Create your views here.


def home_page(request):
    articulos = Articulo.objects.filter(
        pub_date__lte=timezone.now()
    )
    categories = Category.objects.all()
    featured = Articulo.objects.filter(featured=True).filter(
        pub_date__lte=timezone.now()
    )[:3]
    
    context = {
        'articulos': articulos,
        'categories': categories,
        'featured': featured

    }

    return render(request, 'blog/home_page.html', context=context)


class ArticleDetailView(generic.DetailView):
    model = Articulo
    queryset = Articulo.objects.filter(
        pub_date__lte=timezone.now()
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class AboutMeView(generic.TemplateView):
    template_name = 'blog/about_me.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

perfiles/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from perfiles.forms import RegisterForm


# Create your views here.

class PerfilRegistration(FormView):
    template_name = 'perfiles/registration.html'
    form_class = RegisterForm
    success_url = reverse_lazy('perfiles:success')

    def form_valid(self, form):
        form.save()
        return super(PerfilRegistration, self).form_valid(form)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Django Blog</title>
    <link rel="icon" type="image/x-icon" href="/media/logo_adobe_express.ico" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include "navbar.html" %} {% block content %} {% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/blog/about_me.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
  <main class="container">
    <div class="row g-5">
      <div class="col-md-6">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">Acerca de mí</h3>
        <p>
          Hola, soy Luciano, el creador de este sitio. Soy un apasionado/a en la
          programacion y quiero seguir creciendo en este mundo nuevo. En este
          espacio, comparto artículos sobre mi blog de gatos y espero que
          encuentres contenido interesante y útil.
        </p>
        <p>
          No dudes en explorar los artículos y compartir tus pensamientos.
          ¡Gracias por visitar!
        </p>
      </div>
      <div class="col-md-6">
        <img
          src="{% static 'images/foto01.jpg' %} "
          alt="Foto del creador/a"
          class="img-fluid rounded-circle"
          style="width: 450px; height: 480px"
        />
      </div>
    </div>
  </main>
</div>
{% endblock %}

blog/templates/blog/articulo_detail.html
{% extends 'base.html' %} {% block content %} {% load markdown_extras %}

<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
  <main class="container">
    <div class="row g-5">
      <div class="col-md-12">
        <div class="row">
          <div class="d-flex justify-content-between">
            <h1>{{ articulo.titulo }}</h1>
            <div class="align-self-end">
              Publicado: {{ articulo.pub_date.date }}
            </div>
          </div>
        </div>
        <hr class="d-none d-md-block my-2 mb-3 mt-2" />
        {% if articulo.imagen %}
        <div class="text-center">
          <img src="{{ articulo.imagen.url }}" class="img-fluid" alt="imagen" />
        </div>
        {% endif %}

        <p>{{ articulo.cuerpo | markdown | safe }}</p>
      </div>
    </div>
  </main>
</div>

{% endblock content %}

blog/templates/blog/featured.html
<div id="carouselIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button
      type="button"
      data-bs-target="#carouselIndicators"
      data-bs-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselIndicators"
      data-bs-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselIndicators"
      data-bs-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div class="carousel-inner">
    {% for f in featured %}
    <div class="carousel-item {% if f == featured|first %}active{% endif %}">
      <div
        class="px-5 p-md-5 mb-4 rounded text-bg-success bg-gradient"
        style="height: 300px"
      >
        <div class="col-md-10 px-5 mx-5">
          <h1 class="display-4 fw-bold px-5">{{ f.titulo }}</h1>
          <p class="lead my-3 px-5">{{ f.overview }}</p>
          <p class="lead mb-0 px-5">
            <a href="{{ f.get_absolute_url }}" class="text-white fw-bold"
              >Continue reading...</a
            >
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselIndicators"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselIndicators"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

blog/templates/blog/home_page.html
{% extends 'base.html' %} {% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
  <main class="container">
    <div class="row g-5">
      <div class="col-md-12">{% include "blog/featured.html" %}</div>
    </div>

    <div class="row g-5">
      <div class="col-md-8">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">Más Artículos</h3>
        {% for article in articulos %}
        <article class="blog-post">
          <h2 class="blog-post-title mb-1">
            <a
              href="{{ article.get_absolute_url }}"
              style="text-decoration: none"
              class="text-black"
            >
              {{ article.titulo }}
            </a>
          </h2>
          <p>{{ article.overview }}</p>
          <p class="blog-post-meta">
            {{ article.pub_date.date }}. {{article.autor}}
          </p>
          <hr />
        </article>
        {% endfor %}
      </div>

      <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem">
          <div class="p-4 mb-3 bg-light rounded">
            <h4 class="fst-italic">Sobre</h4>
            <p class="mb-0">
              Información adicional sobre lo que se encuentra dentro de esta
              página.
            </p>
          </div>

          <div class="p-4">
            <h4 class="fst-italic">Más Cosas?</h4>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock content %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"
      >Cat<span class="text-danger">Smash</span></a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about_me' %}">Acerca de mi</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Categorías
          </a>
          <ul class="dropdown-menu">
            {% for category in categories %}
            <li><a class="dropdown-item" href="#">{{ category.titulo }}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search" action="" method="get">
        <input
          name="search"
          class="form-control me-2"
          type="search"
          placeholder="Buscar"
          aria-label="Search"
        />
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
      {% if user.is_authenticated %}
      <a
        class="btn btn-outline-primary ms-2"
        href="{% url 'logout' %}"
        role="button"
        >Sign Out</a
      >
      {% else %}
      <a
        class="btn btn-outline-primary ms-2"
        href="{% url 'login' %}"
        role="button"
        >Sign In</a
      >
      {% endif %}
    </div>
  </div>
</nav>

perfiles/templates/perfiles/registration.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
  <main class="container">
    <div class="row g-5">
      <div class="col-md-3"></div>

      <div class="col-md-6">
        <div class="w-100 m-auto text-center">
          <form method="POST" class="form-group">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-success">Register</button>
          </form>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </main>
</div>
{% endblock %}

perfiles/templates/perfiles/success_registration.html
{% extends 'base.html' %} {% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
  <main class="container">
    <div class="row g-5">
      <div class="col-md-3"></div>

      <div class="col-md-6">
        <div class="w-100 m-auto text-center">
          <h1>Registro Exitoso</h1>
          <a
            class="btn btn-outline-primary mb-5"
            href="{% url 'login' %}"
            role="button"
            >Sign In</a
          >
        </div>
      </div>

      <div class="col-md-3"></div>
    </div>
  </main>
</div>
{% endblock %}